version: '3.5'
services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    depends_on:
      - mysql
